### ISSUE TITLE
The effects of checkpoint

### ISSUE THREAD

**Issue by cesargm2015** [ryansmcgee/seirsplus#12]
When I set a checkpoint between t=15 and t=75, I was expecting to see something like this:

<img width="874" alt="Screen Shot 2020-04-11 at 14 11 53" src="https://user-images.githubusercontent.com/11653860/79050187-c8438800-7bfe-11ea-95c6-e37a51d8a357.png">

The blue curve represents the number of infected people if no restrictions are applied. The green curve is during a simulated quarantine supposing a social contact reduction of 50% (that is, beta is cut in half) at time t=15 and goes back to the original value at the end of the checkpoint (I know this is different in the real world, just for the sake of simplicity).

But this is what I'm getting from seirsplus:

<img width="1033" alt="Screen Shot 2020-04-11 at 14 12 39" src="https://user-images.githubusercontent.com/11653860/79050262-3daf5880-7bff-11ea-926b-fafc8079aac0.png">

The checkpoint doesn't seem to take any effect. Below is a print of the settings I'm using:

<img width="717" alt="Screen Shot 2020-04-11 at 14 19 44" src="https://user-images.githubusercontent.com/11653860/79050338-bca49100-7bff-11ea-8d84-c1fc4472b2e3.png">

What am I getting wrong?

**Comment by ryansmcgee** [comment]
The checkpoints are both being applied early relative to when the main wave takes off given your parameters, and what is happening during that phase is difficult to see due to the y axis being dominated by the larger peak. What does it look like if you only plot up to time 80, say? I suspect your reduction of beta is having an effect during that window, but it's just not visible in the plot. Also, your reduced beta corresponds to a R value of 1.92, which is still well above 1, so I wouldn't expect a drop in new cases, just a slowing of the rate of spread. If after looking into these aspects you still suspect something is wrong the checkpoints, please do let me know.
